# .golangci.yml
# Configuration for golangci-lint
version: "2"

linters:
  default: none
  enable:
    # Keep only the most important linters
    - govet # Official Go vet tool
    - unused # Check for unused code
    - misspell # Spell checking
    - gocyclo # Complexity checking
    - unconvert # Unnecessary type conversions
    - unparam # Unused parameters
    - bodyclose

    # Optional quality checks (enable if you want stricter checking)
    # - errcheck
    # - staticcheck
    # - gocritic
    # - ineffassign
    # - lll
  settings:
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0

  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0

  # Make issues output unique by line.
  # Default: true
  uniq-by-line: false

  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # It's a super-useful option for integration of golangci-lint into existing large codebase.
  # It's not practical to fix all existing issues at the moment of integration:
  # much better don't allow issues in new code.
  # Default: false
  new: true

  # Show only new issues created after the best common ancestor (merge-base against HEAD).
  # Default: ""
  new-from-merge-base: main

  # Show only new issues created after git revision `REV`.
  # Default: ""
  new-from-rev: HEAD

  # Show issues in any part of update files (requires new-from-rev or new-from-patch).
  # Default: false
  whole-files: true

  # Fix found issues (if it's supported by the linter).
  # Default: false
  fix: true

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
