# .golangci.yml
# Configuration for golangci-lint
version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/rescp17/lanFileSharer
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  default: none
  enable:
    # Keep only the most important linters
    - govet          # Official Go vet tool
    - unused         # Check for unused code
    - misspell       # Spell checking
    - gocyclo        # Complexity checking
    - unconvert      # Unnecessary type conversions
    - unparam        # Unused parameters
    
    # Optional quality checks (enable if you want stricter checking)
    # - bodyclose
    # - errcheck
    # - staticcheck
    # - gocritic
    # - ineffassign
    # - lll

issues:
  exclude-rules:
    # Relax rules for test files
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl
        - gosec
        - errcheck
        - lll
    # Ignore underscore in package name warnings
    - path: pkg/
      text: "don't use an underscore in package name"
    # Ignore line length for generated code
    - linters:
        - lll
      source: "^//go:generate "
    # Ignore common errcheck issues
    - linters:
        - errcheck
      text: "Error return value of.*Close.*is not checked"
    - linters:
        - errcheck
      text: "Error return value of.*RemoveAll.*is not checked"
    - linters:
        - errcheck
      text: "Error return value of.*Encode.*is not checked"
    - linters:
        - errcheck
      text: "Error return value of.*Fprintf.*is not checked"
    - linters:
        - errcheck
      text: "Error return value.*recover.*is not checked"
    # Ignore some magic numbers
    - linters:
        - mnd
      text: "Magic number: (10|20|30|100|1000|1024), in"
    # Ignore file permission issues in tests
    - path: _test\.go
      linters:
        - gosec
      text: "G30[1-6]:"

  exclude-use-default: false
  max-issues-per-linter: 50  # Limit each linter to report max 50 issues
  max-same-issues: 10        # Limit same issue to be reported max 10 times